table Localidades
	lineageTag: 4f41ccdc-b712-44f3-a10b-88baf3fb5852

	column Estado
		dataType: string
		lineageTag: fc64df8f-c2b9-4577-95fb-76175d8d73da
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column UF
		dataType: string
		lineageTag: e8ba3d0a-7c37-47b2-9151-ccf5434cc863
		summarizeBy: none
		sourceColumn: UF

		annotation SummarizationSetBy = Automatic

	column Região
		dataType: string
		lineageTag: faf7e5af-1ebe-47b8-9375-2a058c8064b6
		summarizeBy: none
		sourceColumn: Região

		annotation SummarizationSetBy = Automatic

	partition Localidades = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\User\Documents\PROCESSOS SELETIVOS\universia - santander - estágio\Business Case Universia.xlsx"), null, true),
				    Localidades_Sheet = Fonte{[Item="Localidades",Kind="Sheet"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(Localidades_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}}),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Tipo Alterado", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Estado", type text}, {"UF", type text}, {"Região", type text}})
				in
				    #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

